[package]
name = "jeebie"
version = "0.1.0"
authors = ["Valerio Pipolo <valep27@gmail.com>"]

[dependencies]
clippy = {version = "*", optional = true}
piston_window = "0.53.0"
image = "0.10.0"

[features]
default=[]
